"""many-to-many fix

Revision ID: 02bf5cc74b26
Revises: 42bf13bda877
Create Date: 2026-01-13 19:25:38.011968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02bf5cc74b26'
down_revision: Union[str, Sequence[str], None] = '42bf13bda877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('botcommand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['botcommand_id'], ['botcommands.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'botcommand_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    # ### end Alembic commands ###
