"""requests table

Revision ID: 8185df325706
Revises: df144c2355f9
Create Date: 2026-02-21 10:33:25.076831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8185df325706'
down_revision: Union[str, Sequence[str], None] = 'df144c2355f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_request',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    # sa.Column('sended_pic_url', sa.String(), nullable=False),
    sa.Column('send_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_request')
    # ### end Alembic commands ###
