"""width and height of attachment

Revision ID: 8397fee27e3a
Revises: 8185df325706
Create Date: 2026-03-13 21:58:59.765980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8397fee27e3a'
down_revision: Union[str, Sequence[str], None] = '8185df325706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('attachment', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachment', 'height')
    op.drop_column('attachment', 'width')
    # ### end Alembic commands ###
