"""remove minio_url from attachment table

Revision ID: b2ccfce17ee4
Revises: a35e46ebf19a
Create Date: 2026-01-11 22:31:40.557843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ccfce17ee4'
down_revision: Union[str, Sequence[str], None] = '42f9980ca1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachment', 'minio_file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('minio_file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
