"""fill_db

Revision ID: df144c2355f9
Revises: d11d4cbf9e35
Create Date: 2026-01-13 19:52:55.449191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'df144c2355f9'
down_revision: Union[str, Sequence[str], None] = 'd11d4cbf9e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """Fill initial data: roles, botcommands, admins"""
    # ### Roles ###
    op.bulk_insert(
        sa.table(
            'roles',
            sa.column('id', sa.Integer),
            sa.column('name', sa.String),
        ),
        [
            {'id': 1, 'name': 'admin'},
            {'id': 2, 'name': 'user'},
        ]
    )

    # ### Bot commands ###
    op.bulk_insert(
        sa.table(
            'botcommands',
            sa.column('id', sa.Integer),
            sa.column('name', sa.String),
        ),
        [
            {'id': 1, 'name': 'start'},
            {'id': 2, 'name': 'find'},
            {'id': 3, 'name': 'parse'},
        ]
    )

    # ### Admin users ###
    op.bulk_insert(
        sa.table(
            'users',
            sa.column('id', postgresql.BIGINT),  # чтобы влез Telegram ID
            sa.column('user_name', sa.String),
            sa.column('role_id', sa.Integer),
        ),
        [
            {'id': 0, 'user_name': 'YOUR_USERNAME', 'role_id': 1},
            {'id': 1, 'user_name': 'YOUR_USERNAME', 'role_id': 1},
            {'id': 2, 'user_name': 'YOUR_USERNAME', 'role_id': 1},
        ]
    )
    
    # ### Permissions ###
    op.bulk_insert(
        sa.table(
            'permissions',
            sa.column('role_id', sa.Integer),
            sa.column('botcommand_id', sa.Integer),
        ),
        [
            {'role_id': 1, 'botcommand_id': 1}, # admin
            {'role_id': 1, 'botcommand_id': 2}, # admin
            {'role_id': 1, 'botcommand_id': 3}, # admin
            
            {'role_id': 2, 'botcommand_id': 1}, # user
            {'role_id': 2, 'botcommand_id': 2}, # user
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE id IN (0, 1, 2)")
    op.execute("DELETE FROM botcommands WHERE name IN ('start', 'find', 'parse')")
    op.execute("DELETE FROM roles WHERE id IN (1, 2)")
    # ### end Alembic commands ###
